export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE__FAIL = 'UPLOAD_FILE_FAIL'
export const UPLOAD_FILE__RESET = 'UPLOAD_FILE_RESET'